tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "cask"
brew "fzf"
brew "ghq"
brew "git"
brew "go"
brew "lv"
brew "mas"
brew "nvm"
brew "openjdk"
brew "pipenv"
brew "pyenv"
brew "rbenv"
brew "tmux"
brew "wget"
cask "adoptopenjdk8"
cask "alfred"
cask "android-studio"
cask "github"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "java"
cask "miniconda"
cask "sketch"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Apple Configurator 2", id: 1037126344
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
