#! /usr/bin/env bash

# Path settings
DOTPATH=${DOTPATH:-$HOME/.dotfiles}

# load environment
source $DOTPATH/etc/env.sh

println "Initialize..."
source $DOTPATH/etc/init.sh

println "Deploying..."
source $DOTPATH/etc/deploy.sh

